<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<package format="3">
  <name>theimc_bringup</name>
  <version>7.0.0</version>

  <description>ROS2 Humble Packages for slampibot</description>
  <maintainer email="jeff@todo.com">erail</maintainer>
  <license>Apache 2.0</license>
  <author email="jeff@todo.com">Leo Cho</author>

  <depend>rclpy</depend>
  <depend>message_filters</depend>
  <depend>rviz2</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <!-- D435 RGB-D mapping and localization. -->
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>rtabmap_sync</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>rtabmap_viz</exec_depend>
  <exec_depend>rtabmap_rviz_plugins</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>